import type { Project } from "../types/project.types";

import {
  AuroraThumb,
  BlackCubeThumb,
  CurveThumb,
  DraftThumb,
  SayanBayThumb,
  StoneLodgeThumb,
} from "../components/ProjectThumbs";

export const MOCK_PROJECTS: ReadonlyArray<Project> = [
  {
    id: "UP-2604-09",
    name: "역삼 Aurora",
    address: "서울 강남구 역삼동 123-4",
    category: "HOTEL · ICONIC",
    areaLabel: "1,240㎡",
    floors: "18F/B3",
    updatedLabel: "3일 전",
    status: "done",
    Thumbnail: AuroraThumb,
  },
  {
    id: "UP-2604-08",
    name: "강릉 Sayan Bay",
    address: "강원 강릉시 사천면 산토리 88-1",
    category: "RESORT · OCEAN",
    areaLabel: "5,820㎡",
    floors: "5F",
    updatedLabel: "1주 전",
    status: "done",
    Thumbnail: SayanBayThumb,
  },
  {
    id: "UP-2604-12",
    name: "해운대 Curve",
    address: "부산 해운대구 우동 1408",
    category: "HOTEL · FUTURIST",
    areaLabel: "2,940㎡",
    floors: "32F",
    updatedLabel: "방금 전",
    status: "work",
    Thumbnail: CurveThumb,
  },
  {
    id: "UP-2604-06",
    name: "평창 Stone Lodge",
    address: "강원 평창군 진부면 동산리 102",
    category: "RESORT · MOUNTAIN",
    areaLabel: "8,100㎡",
    floors: "4F",
    updatedLabel: "2주 전",
    status: "done",
    Thumbnail: StoneLodgeThumb,
  },
  {
    id: "UP-2604-04",
    name: "판교 Black Cube",
    address: "경기 성남시 분당구 삼평동 681",
    category: "OFFICE · MINIMAL",
    areaLabel: "3,460㎡",
    floors: "22F",
    updatedLabel: "3주 전",
    status: "done",
    Thumbnail: BlackCubeThumb,
  },
  {
    id: "UP-2604-11",
    name: "제주 Coastal",
    address: "제주 서귀포시 안덕면 사계리 (예정)",
    category: "HOTEL · 미선택",
    areaLabel: "—",
    floors: "—",
    updatedLabel: "5일 전",
    status: "draft",
    Thumbnail: DraftThumb,
  },
];

export const STATS = [
  { label: "전체 프로젝트", value: "12", suffix: "건", trend: "이번 달 +3" },
  { label: "생성 완료", value: "8", suffix: "건", emphasized: true },
  { label: "총 합성 면적", value: "142,830", suffix: "㎡" },
  { label: "예상 사업비 합계", value: "2,840", suffix: "억 원" },
] as const;
